Makefile, src/Main.hs, src/Result.hs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/tokstyle/1)
=> Hacks for OSX stdlib support.

.travis.yml, src/Main.hs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/tokstyle/2)
=> Add travis config.

.gitignore, Setup.hs, Setup.lhs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/tokstyle/3)
=> Use Setup.lhs instead of Setup.hs for uniformity.

.gitignore
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/tokstyle/4)
=> Add .stack-work to .gitignore.

src/Main.hs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/tokstyle/7)
=> Remove redundant `do` from unbound monadic expression.

.leaf.yml, .travis.yml, tokstyle.cabal
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/tokstyle/6)
=> Use yaml expansion script for Travis config.

appveyor.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/tokstyle/9)
=> Add appveyor configuration.

LICENSE.md, tokstyle.cabal
Taken from https://www.gnu.org/licenses/agpl-3.0.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/tokstyle/11)
=> Use official markdown license for AGPLv3.

.travis.yml, appveyor.yml, src/Checks/Naming.hs, src/Main.hs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/tokstyle/12)
=> Updates to new toxcore code changes.

src/Checks/Naming.hs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/tokstyle/13)
=> Fix non-exhaustive pattern match.

.travis.yml, BUILD.bazel, appveyor.yml, src/Main.hs, src/Tokstyle/C.hs, src/Tokstyle/C/Naming.hs, src/Tokstyle/Cimple.hs, src/Tokstyle/Cimple/Lexer.x, src/Tokstyle/Cimple/Parser.y, src/Tokstyle/Result.hs, stack.yaml, tokstyle.cabal
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/tokstyle/17)
=> Add a parser for simplified C as used in toxcore.

BUILD.bazel, src/Tokstyle/Cimple.hs, src/Tokstyle/Sources.hs, tokstyle.cabal, tools/BUILD.bazel, tools/check-c.hs, tools/check-cimple.hs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/tokstyle/18)
=> Split tokstyle into check-c and check-cimple.

BUILD.bazel, src/Tokstyle/Cimple.hs, src/Tokstyle/Cimple/Parser.y, src/Tokstyle/Sources.hs, tokstyle.cabal, tools/BUILD.bazel, tools/check-c.hs, tools/check-cimple.hs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/tokstyle/19)
=> Update to new way of specifying dependencies on base packages.

.travis.yml, BUILD.bazel, test/Tokstyle/CimpleSpec.hs, test/testsuite.hs, tokstyle.cabal, tools/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/21)
=> Rename repo to hs-tokstyle and add a test.

.travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/20)
=> Start building releases on tags for tokstyle.

BUILD.bazel, tokstyle.cabal
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/25)
=> Release v0.0.2.

BUILD.bazel, tokstyle.cabal, tools/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/26)
=> Use hazel to manage Haskell package versions.

BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/28)
=> Use happy_parser and alex_lexer macros for code generation.

.leaf.yml, appveyor.yml, stack.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/29)
=> Format yaml files according to yamllint's requirements.

src/Tokstyle/Sources.hs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/30)
=> Add "state" module to the list of toxcore sources to parse.

BUILD.bazel, appveyor.yml, tools/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/35)
=> Use new rules_haskell name for bazel 2.1.1.

BUILD.bazel, src/Tokstyle/Cimple.hs, tokstyle.cabal, tools/BUILD.bazel, tools/check-cimple.hs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/36)
=> Support command line arguments in check-cimple.

BUILD.bazel, tools/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/37)
=> Use new location of the hazel_library bazel macro.

.travis.yml, BUILD.bazel, expand_yacc.pl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/39)
=> Add program to expand parameterised productions in .y files.

.travis.yml, BUILD.bazel, expand_yacc.pl, src/Tokstyle/Cimple/Lexer.x, src/Tokstyle/Cimple/Parser.y, test/Tokstyle/CimpleSpec.hs, tools/BUILD.bazel, tools/dump-tokens.hs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/40)
=> Add comment parsing to Cimple.

expand_yacc.pl, src/Tokstyle/Cimple/AST.hs, src/Tokstyle/Cimple/Analysis.hs, src/Tokstyle/Cimple/Analysis/LoggerCalls.hs, src/Tokstyle/Cimple/Diagnostics.hs, src/Tokstyle/Cimple/Parser.y, src/Tokstyle/Cimple/TraverseAst.hs, tokstyle.cabal
Avoid any dynamic format strings, even ones like `cond ? "str1" : "str2"`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/45)
=> Check that LOGGER macros are only called with string literals.

BUILD.bazel, Procfile, src/Tokstyle/Cimple/AST.hs, src/Tokstyle/Cimple/IO.hs, src/Tokstyle/Cimple/Lexer.x, src/Tokstyle/Cimple/Parser.y, src/Tokstyle/Cimple/Tokens.hs, tokstyle.cabal, web/Tokstyle/App.hs, web/webservice.hs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/46)
=> Add JSON HTTP endpoint for Cimple checks.

BUILD.bazel, tokstyle.cabal
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/50)
=> Release version 0.0.5.

.travis.yml
We moved to travis-ci.com and the encryption key changed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/51)
=> Update travis encrypted github token.

src/Tokstyle/Cimple/Analysis/GlobalFuncs.hs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/52)
=> Fix error message: functions are declared, not defined.

.travis.yml
They have already been built through the pull request, so building it
again on master is pointless. If anything breaks, we'll catch it in the
nightly build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/54)
=> Avoid double-building commits to master.

BUILD.bazel, tokstyle.cabal
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/59)
=> Release version 0.0.6.

.github/release-drafter.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/60)
=> Add release-drafter configuration.

.cirrus.yml, .github/workflows/ci.yml, BUILD.bazel, tokstyle.cabal
This uploads a package candidate on each master build. We will still need a
production build on each tag, later.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/62)
=> chore: Add github workflow for cabal build and hackage upload.

.cirrus.yml, src/Tokstyle/C.hs, src/Tokstyle/Result.hs
We don't officially support any older version anymore, though it might work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/63)
=> chore: Upgrade to ghc-8.10.3

.cirrus.yml, .github/workflows/ci.yml, src/Tokstyle/C/Naming.hs, src/Tokstyle/Result.hs
Not on pull requests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/64)
=> chore: Publish to hackage only on push.

.cirrus.yml, BUILD.bazel, src/Tokstyle/Cimple/Analysis.hs, src/Tokstyle/Cimple/Analysis/DeclaredOnce.hs, src/Tokstyle/Cimple/Analysis/DeclsHaveDefns.hs, src/Tokstyle/Cimple/Analysis/DocComments.hs, src/Tokstyle/Cimple/Analysis/ForLoops.hs, src/Tokstyle/Cimple/Analysis/FuncPrototypes.hs, src/Tokstyle/Cimple/Analysis/FuncScopes.hs, src/Tokstyle/Cimple/Analysis/GlobalFuncs.hs, src/Tokstyle/Cimple/Analysis/LoggerCalls.hs, src/Tokstyle/Cimple/Analysis/LoggerNoEscapes.hs, src/Tokstyle/Cimple/Analysis/VarUnusedInScope.hs, test/Tokstyle/Cimple/AnalysisSpec.hs, tokstyle.cabal, tools/check-cimple.hs, web/Tokstyle/App.hs
Also started a "variable is unused in scope" analyser, but didn't get
very far yet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/70)
=> chore: Update to latest cimple API changes.

src/Tokstyle/Cimple/Analysis.hs, src/Tokstyle/Cimple/Analysis/DocComments.hs, src/Tokstyle/Cimple/Analysis/ForLoops.hs, src/Tokstyle/Cimple/Analysis/FuncPrototypes.hs, src/Tokstyle/Cimple/Analysis/FuncScopes.hs, src/Tokstyle/Cimple/Analysis/GlobalFuncs.hs, src/Tokstyle/Cimple/Analysis/LoggerCalls.hs, src/Tokstyle/Cimple/Analysis/LoggerNoEscapes.hs, src/Tokstyle/Cimple/Analysis/VarUnusedInScope.hs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/72)
=> cleanup: Slight code cleanup: use point-free style more.

.github/settings.yml, .github/workflows/ci.yml, .github/workflows/publish.yml, BUILD.bazel, stack.yaml
On push, we publish the package but we already know the tests passed.
Also, added a stack build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/74)
=> chore: Don't run build on push, only on pull request.

tools/tokstyle, web/Tokstyle/App.hs
This is for users who want to run tokstyle locally but don't want to
build a bunch of Haskell code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/76)
=> feat: Add CLI version of the tokstyle tool using the web API.

.github/workflows/ci.yml, .github/workflows/publish.yml
On push, we publish candidates.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/78)
=> chore: Publish to the real hackage index on release.

.github/workflows/publish.yml
Apparently the latter doesn't work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/79)
=> chore: Use the "released" type of release instead of "published".

.github/workflows/ci.yml, BUILD.bazel, tokstyle.cabal
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/80)
=> chore: Bump version.

.github/workflows/publish.yml, BUILD.bazel, tokstyle.cabal
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/81)
=> chore: Use the same cache key in publish and ci workflows.

.github/workflows/checks.yml, .github/workflows/ci.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/82)
=> chore: Check that GitHub release name matches the one in BUILD.bazel.

.github/workflows/checks.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/84)
=> chore: Fix path to check_release.

.github/workflows/checks.yml, .github/workflows/ci.yml, .github/workflows/publish.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/86)
=> chore: Use the hackage_upload script from ci-tools.

.github/workflows/checks.yml, .github/workflows/publish.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/87)
=> chore: Fix ci-tools checkout.

.github/workflows/checks.yml, .github/workflows/publish.yml
Otherwise, ci-tools gets deleted again.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/88)
=> chore: Checkout current repo before ci-tools.

.github/workflows/checks.yml
The current directory is correct.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/89)
=> chore: Use check_release without the path argument.

.cirrus.yml, .github/settings.yml, .github/workflows/checks.yml, .github/workflows/ci.yml, .github/workflows/publish.yml, web/BUILD.bazel
This way, it doesn't randomly break when cimple changes things.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/93)
=> chore: Add bazel file for the web app.

src/Tokstyle/Linter.hs, src/Tokstyle/Linter/Parens.hs, tokstyle.cabal
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/100)
=> feat: Add check for useless parentheses.

src/Tokstyle/Linter.hs, src/Tokstyle/Linter/LoggerConst.hs, tokstyle.cabal
After creating a Logger, it should never be modified again.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/101)
=> feat: Add check that Logger is always passed as ptr-to-const.

src/Tokstyle/Linter.hs, src/Tokstyle/Linter/CallocArgs.hs, src/Tokstyle/Linter/CallocType.hs, src/Tokstyle/Linter/DocComments.hs, src/Tokstyle/Linter/TypeCheck.hs, stack.yaml, tokstyle.cabal
Ensures that the type passed to `size` is always the same as the type the
result is cast to (minus a pointer).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/102)
=> feat: Check calloc argument order and cast type.

.cirrus.yml, src/Tokstyle/Linter/Parens.hs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/105)
=> feat: Check that function arguments don't have `()` around them.

tools/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/108)
=> chore: Link check-cimple with `-rtsopts` to allow more parallelism.

src/Tokstyle/Linter.hs, src/Tokstyle/Linter/DeclsHaveDefns.hs, src/Tokstyle/Linter/UnsafeFunc.hs, tokstyle.cabal
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/109)
=> feat: Add "unsafe function" checker.

src/Tokstyle/Linter/MallocType.hs
Also allow `char` as an element type in malloc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/111)
=> feat: Stricter checks on malloc size argument.

.cirrus.yml, .github/settings.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/114)
=> chore: Upgrade to latest toktok-stack

src/Tokstyle/Linter.hs, src/Tokstyle/Linter/CallocArgs.hs, src/Tokstyle/Linter/CallocType.hs, src/Tokstyle/Linter/CompoundInit.hs, src/Tokstyle/Linter/DeclaredOnce.hs, src/Tokstyle/Linter/DeclsHaveDefns.hs, src/Tokstyle/Linter/DocComments.hs, src/Tokstyle/Linter/EnumNames.hs, src/Tokstyle/Linter/FuncPrototypes.hs, src/Tokstyle/Linter/FuncScopes.hs, src/Tokstyle/Linter/GlobalFuncs.hs, src/Tokstyle/Linter/LoggerCalls.hs, src/Tokstyle/Linter/MallocType.hs, src/Tokstyle/Linter/MemcpyStructs.hs, src/Tokstyle/Linter/TypedefName.hs, src/Tokstyle/Linter/UnsafeFunc.hs, src/Tokstyle/Linter/VarUnusedInScope.hs, test/Tokstyle/Linter/VarUnusedInScopeSpec.hs, test/Tokstyle/LinterSpec.hs, tokstyle.cabal
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/116)
=> cleanup: Remove Node_format from exemptions list for memcpy.

src/Tokstyle/Linter.hs, src/Tokstyle/Linter/LargeStructParams.hs, tokstyle.cabal
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/117)
=> feat: Add check to make sure we don't pass large structs by value.

src/Tokstyle/Linter/CallbackNames.hs, src/Tokstyle/Linter/CallocArgs.hs, src/Tokstyle/Linter/CallocType.hs, src/Tokstyle/Linter/CompoundInit.hs, src/Tokstyle/Linter/DeclaredOnce.hs, src/Tokstyle/Linter/DeclsHaveDefns.hs, src/Tokstyle/Linter/DocComments.hs, src/Tokstyle/Linter/EnumNames.hs, src/Tokstyle/Linter/ForLoops.hs, src/Tokstyle/Linter/FuncPrototypes.hs, src/Tokstyle/Linter/LargeStructParams.hs, src/Tokstyle/Linter/LoggerCalls.hs, src/Tokstyle/Linter/LoggerConst.hs, src/Tokstyle/Linter/LoggerNoEscapes.hs, src/Tokstyle/Linter/MallocType.hs, src/Tokstyle/Linter/MemcpyStructs.hs, src/Tokstyle/Linter/Parens.hs, src/Tokstyle/Linter/TypeCheck.hs, src/Tokstyle/Linter/TypedefName.hs, src/Tokstyle/Linter/UnsafeFunc.hs, src/Tokstyle/Linter/VarUnusedInScope.hs, stack.yaml, tokstyle.cabal
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/119)
=> perf: Use non-copying TraverseAst.

src/Tokstyle/Common.hs, src/Tokstyle/Linter.hs, src/Tokstyle/Linter/CompoundInit.hs, src/Tokstyle/Linter/FuncScopes.hs, src/Tokstyle/Linter/MemcpyStructs.hs, src/Tokstyle/Linter/MissingNonNull.hs, src/Tokstyle/Linter/NonNull.hs, stack.yaml, tokstyle.cabal
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/122)
=> feat: Check that all pointer arguments have nullability annotations.

src/Tokstyle/Linter/LargeStructParams.hs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/123)
=> chore: Add Packet_Direction enum to exemption list

.github/workflows/ci.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/126)
=> chore: Add common CI workflow, currently includes buildifier.

tokstyle.cabal
So it ends up in our docker image.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/129)
=> chore: Add check-c to the cabal file.

include/netinet/in.h, include/sys/socket.h, include/types.h, tools/check-c.hs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/131)
=> feat: Implement stronger type checking in assignments.

tools/check-c.hs
I should implement all this in cimple at some point. For now, this is
ugly but it works.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/133)
=> cleanup: Slight improvement of this ugly code.

src/Tokstyle/Linter/LargeStructParams.hs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/134)
=> chore: Add a new enum to the exemptions list.

tools/check-c.hs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/135)
=> feat: Check boolean conversions inside logical operators.

tools/check-c.hs, web/webservice.hs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/136)
=> fix: Allow int-to-enum conversion.

include/errno.h, include/sys/select.h, include/sys/time.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/137)
=> feat: Add `select()` to the libc headers.

include/netdb.h, include/stdbool.h, include/stddef.h, test/Tokstyle/Linter/TypeCheckSpec.hs, tokstyle.cabal, tools/check-c.hs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/140)
=> feat: Add stronger checks on casts.

src/Tokstyle/Linter.hs, src/Tokstyle/Linter/BoolReturn.hs, test/Tokstyle/Linter/BoolReturnSpec.hs, tokstyle.cabal, tools/check-c.hs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/142)
=> feat: Check for returning 1/0 in bool functions.

BUILD.bazel, src/Tokstyle/Linter/TypeCheck.hs, tokstyle.cabal, tools/check-c.hs, web/Tokstyle/App.hs
Not complete yet. Disabled in the web service.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/144)
=> feat: Improved type checking.

src/Tokstyle/Common.hs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/147)
=> fix: Add `struct` to the list of types that aren't pointers.

tools/check-c.hs
Refactorings can introduce this error where previously `ptr` was an
array but after refactoring it becomes a pointer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/146)
=> feat: Add check that we don't use `sizeof(ptr)`.

include/errno.h, src/Tokstyle/Linter/TypeCheck.hs
It can now handle struct member access.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/151)
=> feat: Improved type checking some more.

src/Tokstyle/Linter/TypeCheck.hs
The type check is now in theory commutative, so
`unify a b` == `unify b a`.
Whether this is really true, I don't know yet. I'll do a formal proof at
some point later. For now, this works well. One problem is that the
pattern matching order matters, which seems to indicate it might not
actually be commutative.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/155)
=> feat: More improvements and simplifications to type check.

src/Tokstyle/Linter.hs, src/Tokstyle/Linter/Callgraph.hs, src/Tokstyle/Linter/TypeCheck.hs, tokstyle.cabal
This prevents macros referencing local symbols from the scope it's
expanded into.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/156)
=> feat: Add check that all symbols used are defined.

src/Tokstyle/Linter/Callgraph.hs
Current toxcore complies under these exemptions. We just don't want to
add new ones.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/157)
=> feat: Add cycle detection code and exemptions.

src/Tokstyle/Linter/Parens.hs
- OK: `return 3 + 4;`
- NOT OK: `return (3 + 4);`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/159)
=> cleanup: Reject paren-expr in `return`.

BUILD.bazel, src/Tokstyle/Linter/Callgraph.hs, tokstyle.cabal
Lots of exemptions for now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/160)
=> feat: Check for unused symbols.

src/Tokstyle/Linter/TypeCheck.hs
This avoids some use of bottom and makes the type check more precise..
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/161)
=> cleanup: Use type intersection instead of union for `?:`.

src/Tokstyle/Linter.hs, src/Tokstyle/Linter/Assert.hs, tokstyle.cabal
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/163)
=> feat: Prevent non-pure function calls in `assert()`.

src/Tokstyle/Linter/Callgraph.hs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/162)
=> chore: Add SELF_UDP_STATUS_LAN to callgraph exemption list

tools/check-c.hs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/165)
=> fix: Consider types with the same name to be the same type.

src/Tokstyle/Linter/Callgraph.hs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/166)
=> chore: Add more sodium functions to the list of builtins.

src/Tokstyle/Linter/Callgraph.hs, test/Tokstyle/Linter/CallgraphSpec.hs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/167)
=> fix: Consider symbols used in struct definitions as "used".

README.md, src/Tokstyle/Linter/CallocType.hs, stack.yaml, test/Tokstyle/Linter/CallocTypeSpec.hs, test/Tokstyle/Linter/CompoundInitSpec.hs, test/Tokstyle/LinterSpec.hs, tokstyle.cabal
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/168)
=> docs: Add a tutorial for writing linters.

BUILD.bazel, src/Tokstyle/Common.hs, src/Tokstyle/Linter.hs, src/Tokstyle/Linter/BooleanReturn.hs, src/Tokstyle/Linter/Booleans.hs, src/Tokstyle/Linter/CallbackNames.hs, src/Tokstyle/Linter/CallocArgs.hs, src/Tokstyle/Linter/CallocType.hs, src/Tokstyle/Linter/CompoundInit.hs, src/Tokstyle/Linter/DeclsHaveDefns.hs, src/Tokstyle/Linter/DocComments.hs, src/Tokstyle/Linter/FuncScopes.hs, src/Tokstyle/Linter/LargeStructParams.hs, src/Tokstyle/Linter/LoggerConst.hs, src/Tokstyle/Linter/MallocType.hs, src/Tokstyle/Linter/MemcpyStructs.hs, src/Tokstyle/Linter/NonNull.hs, src/Tokstyle/Linter/TypeCheck.hs, src/Tokstyle/Linter/TypedefName.hs, src/Tokstyle/Linter/UnsafeFunc.hs, src/Tokstyle/Linter/VarUnusedInScope.hs, test/Tokstyle/Linter/VarUnusedInScopeSpec.hs, tokstyle.cabal, tools/check-c.hs, tools/check-cimple.hs
This only adds a failing test right now. I'll need to think about the fix, but this test case demonstrates the bug.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/172)
=> fix: Fix `-Wvar-unused-in-scope` for `if` inside `for`.

src/Tokstyle/Linter/Callgraph.hs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/176)
=> chore: Add cmp functions to callgraph exemptions list.

src/Tokstyle/Linter/Callgraph.hs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/178)
=> chore: Exempt bin_pack/unpack functions from `-Wcallgraph`.

src/Tokstyle/Linter/Callgraph.hs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/179)
=> chore: Add missing cmp function.

src/Tokstyle/Linter/TypeCheck.hs
This for the most part avoids bottom types when doing `p - q` for two
variables `p` and `q` of pointer type.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/180)
=> fix: Slight improvement of pointer subtraction type check.

include/msgpack, include/msgpack.h, include/stdint.h, tools/check-c.hs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/183)
=> cleanup: Slightly tighten allowed implicit int conversions.

src/Tokstyle/Linter/TypeCheck.hs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/187)
=> fix: Slightly better support again for pointer arithmetic.

src/Tokstyle/Linter.hs, src/Tokstyle/Linter/SwitchIf.hs, test/Tokstyle/Linter/SwitchIfSpec.hs, tokstyle.cabal
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/188)
=> feat: Add linter to detect `if`s that should be `switch`es.

src/Tokstyle/Linter/SwitchIf.hs
Also simplified the code slightly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/189)
=> docs: Add some documentation to `SwitchIf.shouldDiagnose`.

src/Tokstyle/Linter/LargeStructParams.hs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/193)
=> fix: Add Net_Packet_Type to exemptions for -Wlarge-struct-params.

src/Tokstyle/Linter/CallocArgs.hs, src/Tokstyle/Linter/CallocType.hs, src/Tokstyle/Linter/MallocType.hs, test/Tokstyle/Linter/CallocTypeSpec.hs
See https://github.com/TokTok/c-toxcore/pull/2393
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-tokstyle/197)
=> refactor: Get tokstyle ready for `mem` module changes.

src/Tokstyle/Linter/Callgraph.hs, src/Tokstyle/Linter/CallocArgs.hs, src/Tokstyle/Linter/CallocType.hs, src/Tokstyle/Linter/MallocType.hs, test/Tokstyle/Linter/CallocTypeSpec.hs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-tokstyle/198)
=> fix: Add exemptions for `-Wcallgraph` so we can reenable it.

stack.yaml, tokstyle.cabal
This one is compatible with later alex versions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-tokstyle/201)
=> chore: Increase cimple version dependency to 0.0.17.

stack.yaml, tokstyle.cabal
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-tokstyle/204)
=> chore: Upgrade stack LTS snapshot to 21.9 (GHC 9.4.6).

.cirrus.yml, BUILD.bazel, src/Tokstyle/Linter/TypeCheck.hs, tools/BUILD.bazel, web/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-tokstyle/206)
=> chore: Update to new third_party method for haskell deps.

src/Tokstyle/Linter/Assert.hs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-tokstyle/209)
=> fix: Allow member access in `assert()`.

BUILD.bazel, include/stdint.h, src/Tokstyle/C/Env.hs, src/Tokstyle/C/Linter.hs, src/Tokstyle/C/Linter/BoolConversion.hs, src/Tokstyle/C/Linter/Cast.hs, src/Tokstyle/C/Linter/Conversion.hs, src/Tokstyle/C/Linter/Sizeof.hs, src/Tokstyle/C/Patterns.hs, src/Tokstyle/C/TravUtils.hs, src/Tokstyle/C/TraverseAst.hs, src/Tokstyle/Linter.hs, tokstyle.cabal, tools/BUILD.bazel, tools/check-c.hs
Split the big check-c.hs file into multiple modules to make it more maintainable and easier to extend.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-tokstyle/213)
=> refactor: Rewrite check-c with a TraverseAst pattern.

src/Tokstyle/Linter.hs, src/Tokstyle/SemFmt/EnumUnpack.hs, test/Tokstyle/SemFmt/EnumUnpackSpec.hs, tokstyle.cabal
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-tokstyle/216)
=> feat: Add enum unpack function generator (linter).

src/Tokstyle/C/Linter.hs, src/Tokstyle/C/Linter/Memset.hs, test/Tokstyle/C/Linter/MemsetSpec.hs, tokstyle.cabal
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-tokstyle/218)
=> feat: Add linter to check for memset writing to pointers.

src/Tokstyle/C/Linter/Conversion.hs, src/Tokstyle/Linter/Assert.hs
The "pure function" analysis needs to be written. For now, it's a manual list of allowed functions in assert.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-tokstyle/219)
=> fix: Add some temporary hacks for ordered-events PR.

BUILD.bazel, src/Tokstyle/C/Linter.hs, src/Tokstyle/C/TraverseAst.hs, tools/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-tokstyle/222)
=> cleanup: Refine imports to avoid the meta-module.

BUILD.bazel, tools/BUILD.bazel, web/BUILD.bazel
This way we can do bazel build //... when cross-compiling.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-tokstyle/223)
=> chore: Disable targets for cross-compilation.

include/stdint.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-tokstyle/225)
=> chore: add UINT64_C to stdint.h

src/Tokstyle/Linter/Callgraph.hs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-tokstyle/228)
=> chore: Add support for QueryPerformanceCounter from winapi.

src/Tokstyle/Linter/Callgraph.hs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-tokstyle/229)
=> chore: Also add QueryPerformanceFrequency.

.github/settings.yml, include/linux/if.h, include/netinet/in.h, include/pthread.h, src/Tokstyle/Common/EnumLinter.hs, src/Tokstyle/Linter/Callgraph.hs, src/Tokstyle/SemFmt/EnumFromInt.hs, src/Tokstyle/SemFmt/EnumToString.hs, src/Tokstyle/SemFmt/EnumUnpack.hs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-tokstyle/227)
=> chore: Update `-Wcallgraph` to support symbols from the system PR.

src/Tokstyle/C/Linter/SizeArg.hs, test/Tokstyle/C/Linter/SizeArgSpec.hs, tokstyle.cabal
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-tokstyle/239)
=> test: Add a test for typedef array parameter size check.

tools/check-c.hs
Thanks @robinlinden for pointing this out
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-tokstyle/241)
=> fix: add back a leading slash removed by accident

src/Tokstyle/Linter/MallocCall.hs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-tokstyle/244)
=> fix: Adapt to nullptr now being a constant expression.

src/Tokstyle/Common/Patterns.hs, src/Tokstyle/Linter/CallocArgs.hs, src/Tokstyle/Linter/CallocType.hs, src/Tokstyle/Linter/DeclsHaveDefns.hs, src/Tokstyle/Linter/MallocCall.hs, src/Tokstyle/Linter/MallocType.hs, tokstyle.cabal
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-tokstyle/246)
=> fix: Ignore malloc cast checks in alloc functions.

include/stdint.h, src/Tokstyle/Linter/Callgraph.hs, src/Tokstyle/Linter/TypeCheck.hs, stack.yaml, tokstyle.cabal
Doesn't do anything, but also doesn't crash. Additionally, we now detect when unify may go into an infinite loop and error out.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-tokstyle/249)
=> feat: Add support for bitwise/force types in typecheck.

src/Tokstyle/Linter/Callgraph.hs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-tokstyle/255)
=> fix: add libsodium's unsigned 32bit random function

BUILD.bazel, src/Tokstyle/Linter/TypeCheck.hs, tokstyle.cabal
The former is deprecated.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-tokstyle/257)
=> refactor: Migrate from ansi-wl-pprint to prettyprinter.

src/Tokstyle/Linter/Callgraph.hs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-tokstyle/261)
=> chore: Add `SO_EXCLUSIVEADDRUSE` to known external constants.

src/Tokstyle/Linter/Callgraph.hs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-tokstyle/263)
=> fix: Add missing well-known constant we now use in toxcore.

BUILD.bazel, doc/BUILD.bazel, tools/BUILD.bazel, web/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-tokstyle/264)
=> chore: Add more descriptive/precise tags to bazel build rules.

.circleci/config.yml, .cirrus.yml, BUILD.bazel, src/Tokstyle/Linter/MissingNonNull.hs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-tokstyle/265)
=> chore: Add tox_options.h to the public API.

tokstyle.cabal
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-tokstyle/267)
=> chore: Update language-c module version bounds.

src/Tokstyle/Common.hs, src/Tokstyle/Linter/DocComments.hs, src/Tokstyle/Linter/MissingNonNull.hs, src/Tokstyle/Linter/NonNull.hs, src/Tokstyle/Linter/TypeCheck.hs, stack.yaml, test/Tokstyle/Linter/AssertSpec.hs, test/Tokstyle/Linter/CallbackNamesSpec.hs, test/Tokstyle/Linter/CallocArgsSpec.hs, test/Tokstyle/Linter/DeclaredOnceSpec.hs, test/Tokstyle/Linter/DeclsHaveDefnsSpec.hs, test/Tokstyle/Linter/DocCommentsSpec.hs, test/Tokstyle/Linter/EnumNamesSpec.hs, test/Tokstyle/Linter/FuncPrototypesSpec.hs, test/Tokstyle/Linter/FuncScopesSpec.hs, test/Tokstyle/Linter/GlobalFuncsSpec.hs, test/Tokstyle/Linter/LoggerCallsSpec.hs, test/Tokstyle/Linter/LoggerConstSpec.hs, test/Tokstyle/Linter/LoggerNoEscapesSpec.hs, test/Tokstyle/Linter/MallocTypeSpec.hs, test/Tokstyle/Linter/MemcpyStructsSpec.hs, test/Tokstyle/Linter/MissingNonNullSpec.hs, test/Tokstyle/Linter/NestingSpec.hs, test/Tokstyle/Linter/NonNullSpec.hs, test/Tokstyle/Linter/TypedefNameSpec.hs, test/Tokstyle/Linter/UnsafeFuncSpec.hs, tokstyle.cabal
Also add a bunch more tests for all the linters.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-tokstyle/268)
=> feat: Add support for `non_null`/`nullable` specs on params.

doc/cimple.md, src/Tokstyle/Linter/Nullability.hs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-tokstyle/272)
=> docs: Update tokstyle docs.
