Makefile
src/Main.hs
tokstyle.cabal

This means we can't run it from the tokstyle root anymore, and need to
run directly from toktok-stack, in which we have the c-toxcore directory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/tokstyle/5)

Change paths in tokstyle to assume being run from toktok-stack.

---

src/Tokstyle/Cimple/Parser.y

E.g. `foo_cb myfunc`, meaning the same as `void myfunc(int a)` if there
was a `typedef void foo_cb(int a)` before it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/24)

Allow function declarations using `_cb` types.

---

src/Tokstyle/Cimple/Lexer.x

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/27)

Add `crypto_sign` to the list of known constant prefixes.

---

src/Tokstyle/Cimple/Lexer.x

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/34)

Add `crypto_auth` to the list of known constant prefixes.

---

BUILD.bazel
tools/BUILD.bazel

toktok-stack sets default -Wall -Werror.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/47)

Remove warning flags. These are now default.

---

BUILD.bazel
Procfile
src/Tokstyle/Cimple/AST.hs
src/Tokstyle/Cimple/IO.hs
src/Tokstyle/Cimple/Lexer.x
src/Tokstyle/Cimple/Parser.y
src/Tokstyle/Cimple/Tokens.hs
tokstyle.cabal
tools/BUILD.bazel
web/Tokstyle/App.hs
web/webservice.hs

These were useful because they avoid recompiling all the other code while
testing the lexer, but we now have a test that ensures cabal and bazel
agree, and this makes them disagree.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/48)

Remove cimple-lexer and cimple-parser targets.

---

src/Tokstyle/Cimple/Analysis.hs
src/Tokstyle/Cimple/Analysis/LoggerNoEscapes.hs
tokstyle.cabal

It's a common mistake to add an extra newline character at the end of a
LOGGER format string. These end up needlessly creating double newlines in
client log outputs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/49)

Add check that LOGGER format strings contain no escapes.

---

BUILD.bazel

Tokstyle needs its own .travis.yml for now, because it releases binaries,
unlike (at the moment) all other Haskell projects. Once the standard
Travis config template supports binary releases, we'll remove this
opt-out and start using that template.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/55)

Explicitly opt-out of standard Travis template.

---

.github/settings.yml
tokstyle.cabal

The interface we expose is the "run all analyses" function.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/56)

Hide the Analysis implementation modules from the library.

---

.cirrus.yml
src/Tokstyle/Cimple/Analysis.hs
src/Tokstyle/Cimple/Analysis/ForLoops.hs
src/Tokstyle/Cimple/Analysis/GlobalFuncs.hs
test/Tokstyle/Cimple/AnalysisSpec.hs
tokstyle.cabal
tools/check-cimple.hs
web/Tokstyle/App.hs

The for loop init decl should either be a variable declaration like
`int i = 0` or an assignment like `i = 0`. This disallows for example
`int i` as an init-decl (it's uninitialised) or some random other
expression that's not an assignment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/67)

feat: Require that for-init-decls have one of 2 formats.

---

.cirrus.yml
src/Tokstyle/Cimple/Analysis.hs
src/Tokstyle/Cimple/Analysis/DocComments.hs
src/Tokstyle/Cimple/Analysis/ForLoops.hs
src/Tokstyle/Cimple/Analysis/FuncPrototypes.hs
src/Tokstyle/Cimple/Analysis/LoggerCalls.hs
src/Tokstyle/Cimple/Analysis/LoggerNoEscapes.hs
test/Tokstyle/Cimple/AnalysisSpec.hs
tokstyle.cabal
tools/check-cimple.hs
web/Tokstyle/App.hs

This currently only works for Doxygen comments, i.e. ones starting with
`/**`. This is because we can't distinguish between random comments in
the middle of the file and function comments. Ultimately, we'll want all
function comments to be doxygen style comments anyway.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/68)

feat: Check that doc comments match for function decl/defn.

---

src/Tokstyle/Cimple/Analysis.hs
src/Tokstyle/Cimple/Analysis/DeclaredOnce.hs
src/Tokstyle/Cimple/Analysis/DeclsHaveDefns.hs
src/Tokstyle/Cimple/Analysis/DocComments.hs
src/Tokstyle/Cimple/Analysis/ForLoops.hs
tokstyle.cabal

This avoids keeping function declarations around for which we deleted the
implementation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/69)

feat: Add check that every declaration has a matching definition.

---

.cirrus.yml
src/Tokstyle/Cimple/Analysis/DeclaredOnce.hs
src/Tokstyle/Cimple/Analysis/DeclsHaveDefns.hs
src/Tokstyle/Cimple/Analysis/DocComments.hs
src/Tokstyle/Cimple/Analysis/ForLoops.hs
src/Tokstyle/Cimple/Analysis/FuncPrototypes.hs
src/Tokstyle/Cimple/Analysis/LoggerCalls.hs
src/Tokstyle/Cimple/Analysis/LoggerNoEscapes.hs
src/Tokstyle/Cimple/Analysis/VarUnusedInScope.hs
tokstyle.cabal

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/71)

chore: Use simplified TraverseAst API from cimple.

---

.github/workflows/checks.yml

It doesn't belong in github-tools.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/85)

chore: Use ci-tools for check_release.

---

web/Tokstyle/App.hs

Otherwise, you get:
```
bash$ curl https://tokstyle.herokuapp.com/source
https://github.com/TokTok/hs-tokstylebash$
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/90)

chore: Add newline to the `/source` endpoint in the web app.

---

.github/workflows/ci.yml
BUILD.bazel

Lots of stuff doesn't work with ghc 9, so it's all back to 8.10.3 now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/94)

chore: Use standard CI workflow now that it's downgraded.

---

src/Tokstyle/Linter.hs
src/Tokstyle/Linter/TypeCheck.hs
src/Tokstyle/Linter/TypedefName.hs
src/Tokstyle/Linter/VarUnusedInScope.hs
tokstyle.cabal

I.e. we should write
```c
typedef struct Foo { ... } Foo;
```
and not
```c
typedef struct Foo_s { ... } Foo;
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/96)

feat: Check that typedef structs share the name with the struct.

---

src/Tokstyle/Linter.hs
src/Tokstyle/Linter/MallocType.hs
tokstyle.cabal

It's used for byte arrays and one exemption in `LAN_discovery.c` because
of Microsoft® Windows™ Weirdness™. Generally, we should use calloc just
to be safe and have zero-initialised data structures. For byte and int16
arrays, we allow uninitialised allocations for efficiency reasons.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/103)

feat: Check that `malloc` is only used for builtin types.

---

tokstyle.cabal
tools/BUILD.bazel
tools/check-cimple.hs

This saves about 25-28% of overall wallclock time when running with 3 or
4 cores (on my machine).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/106)

perf: Run tokstyle checkers in parallel.

---

BUILD.bazel
src/Tokstyle/Linter.hs
src/Tokstyle/Linter/MemcpyStructs.hs
tokstyle.cabal
tools/BUILD.bazel
web/BUILD.bazel

`memcpy` doesn't do any type checking, so there's no guarantee that the
thing copied from is the same type as the thing copied to. Sometimes
that's useful, but most of the time it's potentially unsafe. Usually it's
also more typing than a simple assignment. E.g.
```c
memcpy(&some_struct, &other_struct, sizeof(Struct_Type));
```
vs.
```c
some_struct = other_struct;
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/104)

feat: Check that memcpy is not used where assignment could be used.

---

src/Tokstyle/Linter/MallocType.hs
src/Tokstyle/Linter/UnsafeFunc.hs

It will look like:
```
c-toxcore/toxcore/Messenger.c:2478: function `sprintf' should not be used, because it has no way of bounding the number of characters written; use snprintf instead
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/110)

feat: Add more functions to the unsafe list with explanations.

---

src/Tokstyle/Linter/MemcpyStructs.hs

These are now fixed in toxcore.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/112)

cleanup: Remove `Cmp_data` exemptions.

---

include/inttypes.h
include/opus
include/pthread.h
include/vpx
tokstyle.cabal
tools/BUILD.bazel
tools/check-c.hs

Also we now disallow implicit `bool` conversion from `unsigned int`.
We allow `int`, because in C, `a == b` has type `int`. We'll gradually
disallow the use of `int` in toxcore and require sized ints (`intNN_t`)
everywhere. Then we'll also disallow implicit conversion from sized int
to bool.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/130)

feat: Add support for everything needed by toxav.

---

tools/check-c.hs

We've fixed all of these now, so the check can be enabled.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/139)

fix: Remove exemption for binary expressions in if stmts.

---

src/Tokstyle/Linter/Constness.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/148)

cleanup: Slight code improvements.

---

include/pthread.h
tools/check-c.hs

This only checks `==` and `!=`. Any other bool-to-T conversions aren't
checked yet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/149)

feat: Check for comparisons of bool and non-bool.

---

src/Tokstyle/Linter/Parens.hs

E.g. `a = (3)` or `a = (3 * 2)` should not have parentheses.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/150)

feat: Disallow parens in assignment expressions.

---

src/Tokstyle/Linter.hs
src/Tokstyle/Linter/Booleans.hs
src/Tokstyle/Linter/TypeCheck.hs
test/Tokstyle/Linter/BooleansSpec.hs
tokstyle.cabal
tools/check-cimple.hs

These can be simplified to `x` and `!x` respectively.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/152)

feat: Check for `x == true` and `x == false`.

---

src/Tokstyle/Linter.hs
src/Tokstyle/Linter/BooleanReturn.hs
src/Tokstyle/Linter/TypeCheck.hs
test/Tokstyle/Linter/BooleanReturnSpec.hs
tokstyle.cabal

Functions that only return one of two constant values in any `return`
statement are effectively boolean functions but use `int` instead. This
linter warns about those functions. It ignores functions with `handle`
in the name because those may be callbacks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/153)

feat: Add check for functions that could return `bool`.

---

src/Tokstyle/Linter/DocComments.hs

This diagnostic was completely ignored for most functions after we added
nullability annotations to everything.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/170)

fix: Fix `-Wdoc-comments` on functions with `non_null`.

---

tokstyle.cabal
tools/BUILD.bazel
tools/check-cimple.hs

This currently just shows how long parsing takes and then how long
linting takes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/174)

feat: Output timing details for check-cimple.

---

BUILD.bazel
src/Tokstyle/Linter.hs
src/Tokstyle/Linter/VarUnusedInScope.hs
test/Tokstyle/Linter/VarUnusedInScopeSpec.hs
tokstyle.cabal
tools/check-cimple.hs

This was done correctly, but we hadn't documented why arrays are
ignored. Ignoring them causes false negatives, but the false positives
are somewhat difficult to avoid. See the tests for two cases in which we
don't want to reduce the scope of arrays but we would want to reduce the
scope of pointers (which are indistinguishable at the use-site).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/175)

test: Add a test to make sure arrays are treated as expected.

---

src/Tokstyle/Linter/Callgraph.hs

This should really be a pattern, but more so, those functions shouldn't
be hidden behind ugly ACCESSOR macros.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/182)

chore: Add some more tox_options functions to the exemptions.

---

src/Tokstyle/Linter/DeclsHaveDefns.hs

Because implementations are provided by `CONST_FUNCTION` and friends,
which tokstyle has no clue about.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/184)

chore: Add tox_private.h to the exemptions list for -Wdecls-have-defns.

---

tools/check-c.hs

This can be a hard to discover bug and compilers don't warn about it.
The one exemption is used in a loop. Maybe that shouldn't be done, but
I'll look into that later.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/185)

fix: Disallow `sizeof(MyStruct*)` with 1 exemption.

---

tools/check-c.hs

This will catch `sizeof(my_vla)`, which doesn't work on systems like
Windows where we don't use VLAs and instead use alloca.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/186)

fix: Disable VLA support to catch more errors.

---

src/Tokstyle/Linter/NonNull.hs

These should always be no-ops when passed a null pointer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/190)

feat: Require that `*_free` and `kill_*` functions are nullable.

---

src/Tokstyle/Linter/SwitchIf.hs
test/Tokstyle/Linter/SwitchIfSpec.hs

A `switch` starts to improve readability when there are many branches
comparing a variable to different enum constants. For 2 branches, we'll
leave it up to the programmer to decide.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/192)

fix: Allow up to 2 if-branches to not be a switch.

---

src/Tokstyle/Linter/Parens.hs
test/Tokstyle/Linter/ParensSpec.hs
tokstyle.cabal

This is used to silence warnings about constant if statements like:
```
if ((true)) {
return 2;
}
return 3;
```
Example: https://github.com/TokTok/c-toxcore/pull/2234
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/191)

fix: Add exemption for in `-Wparens` for `if ((x))`.

---

src/Tokstyle/Linter/Assert.hs

This prevents a warning because it's used in an assert in [#2317](https://github.com/TokTok/c-toxcore/pull/2317)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tokstyle/196)

fix: add shared_key_is_empty(...) to pure functions

---

README.md

This is the version we use in most of our docker images now.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-tokstyle/200)

chore: Update dockerfile documentation to ubuntu 22.04.

---

tokstyle.cabal

Their API broke in 1.0.2.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-tokstyle/202)

chore: Fix ansi-wl-pprint dependency at 0.6.9.

---

tools/check-c.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-tokstyle/203)

fix: Allow implicit conversions to `const void *`.

---

test/Tokstyle/LinterSpec.hs
tools/check-c.hs

zoff wants to use it in toxav.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-tokstyle/205)

fix: Add `randombytes` to exemptions list for charptr cast.

---

BUILD.bazel
tokstyle.cabal
tools/BUILD.bazel
tools/check-cimple.hs
web/BUILD.bazel

The former does additional include checking and normalisation, needed for module dependency checks. We'll change parseFiles to not do that, so we can use it for apigen.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-tokstyle/207)

refactor: Use `parseProgram` instead of `parseFiles`.

---

src/Tokstyle/Linter/Assert.hs
src/Tokstyle/Linter/TypeCheck.hs

If condition and both branches are pure, then the ternary expression is pure as well.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-tokstyle/208)

fix: Allow `a?b:c` in assert.

---

BUILD.bazel
tools/check-c.hs

Currently it hard-codes "clang". This makes it overrideable.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-tokstyle/211)

feat: Add support for passing the path to a C compiler to check-c.

---

src/Tokstyle/Common/EnumLinter.hs
src/Tokstyle/Linter.hs
src/Tokstyle/SemFmt/EnumFromInt.hs
src/Tokstyle/SemFmt/EnumToString.hs
test/Tokstyle/SemFmt/EnumFromIntSpec.hs
test/Tokstyle/SemFmt/EnumToStringSpec.hs
tokstyle.cabal

There are none of these in toxcore, yet, but this will allow us to add them and ensure they stay up-to-date, relieving us from the maintenance burden it would otherwise present.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-tokstyle/214)

feat: Add enum `to_string` check.

---

BUILD.bazel
src/Tokstyle/C/Linter.hs
test/Tokstyle/C/Linter/SizeofSpec.hs
test/Tokstyle/C/LinterSpec.hs
test/Tokstyle/LinterSpec.hs
tokstyle.cabal
tools/check-c.hs

Currently only the `sizeof` linter, but this makes it easy to add more tests later.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-tokstyle/217)

test: Add unit tests for C linters.

---

BUILD.bazel
src/Tokstyle/Linter.hs
src/Tokstyle/Linter/EnumDefines.hs
test/Tokstyle/Linter/EnumDefinesSpec.hs
tokstyle.cabal

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-tokstyle/221)

feat: Add linter to detect sequences of `#defines` that should be enums.

---

src/Tokstyle/Linter.hs
src/Tokstyle/Linter/Nesting.hs
tokstyle.cabal

Right now, `send_crypto_packets` is deeply nested and terrible. Once that's fixed, we can reduce this number by a bit. Generally we should avoid deep nesting and instead extract functions or invert conditions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-tokstyle/224)

feat: Add `-Wnesting` to limit nesting depth in functions.

---

src/Tokstyle/C/Env.hs
src/Tokstyle/C/Linter.hs
src/Tokstyle/C/Linter/Memset.hs
src/Tokstyle/C/Linter/VoidCall.hs
test/Tokstyle/C/Linter/VoidCallSpec.hs
tokstyle.cabal

They must always start with the cast from `void*` to whatever `T*` they are actually handling. This makes it easier to read and understand that the `void*` is actually a `T*`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-tokstyle/231)

feat: `-Wvoid-call` to validate the format of callback handlers.

---

BUILD.bazel
LICENSE
src/Tokstyle/Linter/DeclsHaveDefns.hs

This aligns with the new zig-toxcore-c repo. It is a chore, but better than changing the zig-toxcore-c license to not use https.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-tokstyle/232)

chore: Use GPL license with https.

---

src/Tokstyle/C/Linter/Conversion.hs

We should really do a const removal from array/pointer types for this check, but for now this works.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-tokstyle/234)

fix: Allow non-const array to be assigned to const array.

---

src/Tokstyle/C/Linter/Conversion.hs

C has so many int conversions, it's not worth trying to check them all. Instead, we should try to use sized int types everywhere so this check can catch errors in them.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-tokstyle/235)

fix: Relax int conversions further.

---

doc/cimple.md
doc/generate
src/Tokstyle/Common.hs
src/Tokstyle/Linter.hs
src/Tokstyle/Linter/CallocArgs.hs
src/Tokstyle/Linter/CallocType.hs
src/Tokstyle/Linter/MallocCall.hs
src/Tokstyle/Linter/MallocType.hs
test/Tokstyle/Linter/MallocCallSpec.hs
tokstyle.cabal

Checks that allocation functions like `mem_balloc` are always first assigned to a local variable.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-tokstyle/237)

feat: Add `-Wmalloc-call`.

---

tools/check-c.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-tokstyle/240)

feat: add a check-c run option for a custom include path

---

src/Tokstyle/C/Linter/Conversion.hs
tools/check-c.hs

Also disable float code from cmp.c, which is non-portable and we don't use it anyway.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-tokstyle/243)

fix: Exempt cmp.c from conversion checking.

---

src/Tokstyle/Linter/TypeCheck.hs

This happens when a function is passed as callback to another function which has already seen a different function be passed as callback. We need to unify them against each other (for now, without polymorphism).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-tokstyle/247)

fix: Support delayed type definition for function defns.

---

src/Tokstyle/Linter/TypeCheck.hs

Otherwise we end up with infinite recursion trying to resolve the name.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-tokstyle/248)

fix: Unify struct and name into struct.

---

src/Tokstyle/Linter/Callgraph.hs

Toxcore defines this manually at the moment, but libsodium already does.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-tokstyle/250)

fix: Add missing `crypto_box_MACBYTES`.

---

src/Tokstyle/Linter/Callgraph.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-tokstyle/254)

fix: Add OPUS_SET_VBR, so we can disable it

---

stack.yaml
test/Tokstyle/Linter/CallocTypeSpec.hs
tokstyle.cabal

Colours are now rendered with `\ESC[0;NNm`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-tokstyle/258)

fix: Adapt to prettyprinter changes in cimple.

---

src/Tokstyle/Linter/Callgraph.hs
src/Tokstyle/Linter/EnumNames.hs
src/Tokstyle/Linter/TypedefName.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-tokstyle/260)

fix: Support `_e` suffix for internal cmp enums.

---

doc/BUILD.bazel

The latter is deprecated.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-tokstyle/262)

cleanup: Use `tools` instead of `exec_tools`.

---

test/Tokstyle/Analysis/PointsToSpec.hs

Different versions of the crypto hash could output different values here.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-tokstyle/274)

fix: Don't test for a hard-coded heap location hash.
